name: Android Debug Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [wawapp_client, wawapp_driver]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.6'
        channel: 'stable'
        cache: true
    
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          apps/${{ matrix.app }}/android/.gradle
        key: gradle-${{ runner.os }}-${{ matrix.app }}-${{ hashFiles('apps/${{ matrix.app }}/android/gradle/wrapper/gradle-wrapper.properties', 'apps/${{ matrix.app }}/android/**/*.gradle*') }}
        restore-keys: |
          gradle-${{ runner.os }}-${{ matrix.app }}-
          gradle-${{ runner.os }}-
    
    - name: Cache Pub dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.PUB_CACHE }}
          ~/.pub-cache
        key: pub-${{ runner.os }}-${{ matrix.app }}-${{ hashFiles('apps/${{ matrix.app }}/pubspec.lock') }}
        restore-keys: |
          pub-${{ runner.os }}-${{ matrix.app }}-
          pub-${{ runner.os }}-
    
    - name: Get dependencies
      working-directory: apps/${{ matrix.app }}
      run: flutter pub get
    
    - name: Build APK
      working-directory: apps/${{ matrix.app }}
      run: flutter build apk --debug
      env:
        GRADLE_OPTS: -Dorg.gradle.configuration-cache=true
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.app }}-debug-apk
        path: apps/${{ matrix.app }}/build/app/outputs/flutter-apk/app-debug.apk